sonar.projectKey=FinancialPlanner
sonar.projectName=FinancialPlanner
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/dist/**,**/public/**,**/*.spec.js,**/*.test.js,vite.config.js
sonar.sourceEncoding=UTF-8