import { mount, flushPromises, DOMWrapper } from '@vue/test-utils';
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import LoanTracker from './LoanTracker.vue';
import { repository } from '../services/indexedDbRepository';
import { generateCreditCardInstallments } from '../services/loanCalculations';

vi.mock('../services/indexedDbRepository', () => ({
  repository: {
    getLoans: vi.fn(),
    saveLoans: vi.fn()
  }
}));

const i18nStub = {
  provide: {
    i18n: {
      t: (key) => key,
      formatCurrency: (val) => `$${val}`,
      locale: { value: 'en-US' }
    }
  }
};

function makeCreditLoan(overrides = {}) {
  return {
    id: 'c1',
    type: 'credit',
    friendName: 'Ana',
    loanName: 'TV Financing',
    totalAmount: 300,
    installmentsCount: 3,
    startMonth: '2026-01',
    dueDay: 10,
    cardName: 'Visa',
    notes: '',
    archived: false,
    installments: generateCreditCardInstallments(300, 3, '2026-01', 10),
    ...overrides
  };
}

function makeCasualLoan(overrides = {}) {
  return {
    id: 'p1',
    type: 'casual',
    friendName: 'Bob',
    loanName: 'Concert tickets',
    amountLent: 100,
    dateLent: '2026-01-01',
    notes: '',
    archived: false,
    payments: [],
    ...overrides
  };
}

describe('LoanTracker.vue', () => {
  beforeEach(() => {
    repository.getLoans.mockReset();
    repository.saveLoans.mockReset();
    repository.saveLoans.mockResolvedValue();

    // LoanTracker.vue calls useI18n() directly (unlike other tracker components,
    // which consume it via inject('i18n')), so it exercises useI18n's real
    // localStorage.getItem('fp_locale') read on every mount. Stub a working
    // in-memory Storage so that read succeeds regardless of jsdom/Node's own
    // localStorage wiring in this environment.
    const store = new Map();
    vi.stubGlobal('localStorage', {
      getItem: (key) => (store.has(key) ? store.get(key) : null),
      setItem: (key, value) => store.set(key, String(value)),
      removeItem: (key) => store.delete(key),
      clear: () => store.clear()
    });
  });

  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it('renders the empty state when there are no loans', async () => {
    repository.getLoans.mockResolvedValue([]);

    const wrapper = mount(LoanTracker, { global: i18nStub });
    await flushPromises();

    expect(repository.getLoans).toHaveBeenCalled();
    expect(wrapper.find('.empty-state').exists()).toBe(true);
  });

  it('creates a casual loan through the form and persists it with an empty payments ledger', async () => {
    repository.getLoans.mockResolvedValue([]);

    const wrapper = mount(LoanTracker, { global: i18nStub });
    await flushPromises();

    await wrapper.find('.btn-primary').trigger('click');
    await flushPromises();

    const body = new DOMWrapper(document.body);
    const textInputs = body.findAll('input[type="text"]');
    await textInputs[0].setValue('Carla');
    await textInputs[1].setValue('Moving expenses');
    await body.find('input[type="number"]').setValue(150);
    await body.find('input[type="date"]').setValue('2026-02-01');

    await body.find('form').trigger('submit.prevent');
    await flushPromises();

    expect(repository.saveLoans).toHaveBeenCalled();
    const savedLoans = repository.saveLoans.mock.calls[0][0];
    expect(savedLoans).toHaveLength(1);
    expect(savedLoans[0]).toMatchObject({
      type: 'casual',
      friendName: 'Carla',
      loanName: 'Moving expenses',
      amountLent: 150,
      dateLent: '2026-02-01',
      payments: [],
      archived: false
    });
  });

  it('creates a credit loan through the form and persists installments generated by generateCreditCardInstallments', async () => {
    repository.getLoans.mockResolvedValue([]);

    const wrapper = mount(LoanTracker, { global: i18nStub });
    await flushPromises();

    await wrapper.find('.btn-primary').trigger('click');
    await flushPromises();

    const body = new DOMWrapper(document.body);
    await body.find('input[type="radio"][value="credit"]').setValue();
    await flushPromises();

    const textInputs = body.findAll('input[type="text"]');
    await textInputs[0].setValue('Diego');
    await textInputs[1].setValue('New Laptop');
    await textInputs[2].setValue('Mastercard');

    const numberInputs = body.findAll('input[type="number"]');
    await numberInputs[0].setValue(300);
    await numberInputs[1].setValue(3);
    await body.find('input[type="month"]').setValue('2026-01');
    await numberInputs[2].setValue(10);

    await body.find('form').trigger('submit.prevent');
    await flushPromises();

    expect(repository.saveLoans).toHaveBeenCalled();
    const savedLoans = repository.saveLoans.mock.calls[0][0];
    expect(savedLoans).toHaveLength(1);
    expect(savedLoans[0]).toMatchObject({
      type: 'credit',
      friendName: 'Diego',
      loanName: 'New Laptop',
      totalAmount: 300,
      installmentsCount: 3,
      startMonth: '2026-01',
      dueDay: 10,
      cardName: 'Mastercard'
    });
    expect(savedLoans[0].installments).toEqual(generateCreditCardInstallments(300, 3, '2026-01', 10));
  });

  it('archiving a loan persists archived: true without touching its payment history', async () => {
    const loan = makeCasualLoan({ payments: [{ id: 'pay1', amount: 40, date: '2026-01-05', notes: '' }] });
    repository.getLoans.mockResolvedValue([loan]);

    const wrapper = mount(LoanTracker, { global: i18nStub });
    await flushPromises();

    const archiveBtn = wrapper.findAll('.action-icon-btn')[1];
    await archiveBtn.trigger('click');
    await flushPromises();

    expect(repository.saveLoans).toHaveBeenCalled();
    const savedLoans = repository.saveLoans.mock.calls[0][0];
    expect(savedLoans[0].archived).toBe(true);
    expect(savedLoans[0].payments).toEqual(loan.payments);
  });

  it('toggling an installment marks it paid and stamps a paymentDate', async () => {
    const loan = makeCreditLoan();
    repository.getLoans.mockResolvedValue([loan]);

    const wrapper = mount(LoanTracker, { global: i18nStub });
    await flushPromises();

    await wrapper.find('.loan-card').trigger('click');
    await flushPromises();

    const body = new DOMWrapper(document.body);
    const toggleBtn = body.findAll('.btn-toggle-paid')[0];
    await toggleBtn.trigger('click');
    await flushPromises();

    expect(repository.saveLoans).toHaveBeenCalled();
    const savedLoans = repository.saveLoans.mock.calls[0][0];
    expect(savedLoans[0].installments[0].status).toBe('paid');
    expect(savedLoans[0].installments[0].paymentDate).toMatch(/^\d{4}-\d{2}-\d{2}$/);
  });

  it('editing a credit loan schedule parameter regenerates installments after confirming in the ConfirmDialog (not window.confirm), discarding prior paid status', async () => {
    const confirmSpy = vi.spyOn(globalThis, 'confirm');

    const loan = makeCreditLoan();
    loan.installments[0].status = 'paid';
    loan.installments[0].paymentDate = '2026-01-10';
    repository.getLoans.mockResolvedValue([loan]);

    const wrapper = mount(LoanTracker, { global: i18nStub });
    await flushPromises();

    const editBtn = wrapper.findAll('.action-icon-btn')[0];
    await editBtn.trigger('click');
    await flushPromises();

    const body = new DOMWrapper(document.body);
    const numberInputs = body.findAll('input[type="number"]');
    await numberInputs[1].setValue(4); // installmentsCount 3 -> 4

    await body.find('form').trigger('submit.prevent');
    await flushPromises();

    // No native dialog is ever used (dialog-implementation rule, Directive 1); the save is
    // deferred until the ConfirmDialog's own Confirm button is clicked.
    expect(confirmSpy).not.toHaveBeenCalled();
    expect(repository.saveLoans).not.toHaveBeenCalled();

    // LoanTracker.vue calls useI18n() directly rather than consuming the injected
    // i18nStub (see beforeEach's comment), so button text is the real en-US translation.
    const confirmBtn = body.findAll('button').find(b => b.text() === 'Save Loan' && b.element.closest('.confirm-dialog-content'));
    await confirmBtn.trigger('click');
    await flushPromises();

    const savedLoans = repository.saveLoans.mock.calls[0][0];
    expect(savedLoans[0].installments).toEqual(generateCreditCardInstallments(300, 4, '2026-01', 10));
    expect(savedLoans[0].installments.every(inst => inst.status === 'pending')).toBe(true);
    confirmSpy.mockRestore();
  });

  it('discards the schedule regeneration but keeps other edits when the params ConfirmDialog is cancelled', async () => {
    const loan = makeCreditLoan();
    loan.installments[0].status = 'paid';
    loan.installments[0].paymentDate = '2026-01-10';
    repository.getLoans.mockResolvedValue([loan]);

    const wrapper = mount(LoanTracker, { global: i18nStub });
    await flushPromises();

    const editBtn = wrapper.findAll('.action-icon-btn')[0];
    await editBtn.trigger('click');
    await flushPromises();

    const body = new DOMWrapper(document.body);
    const textInputs = body.findAll('input[type="text"]');
    await textInputs[1].setValue('TV Financing (renegotiated)'); // loanName, a non-param field
    const numberInputs = body.findAll('input[type="number"]');
    await numberInputs[1].setValue(4); // installmentsCount 3 -> 4

    await body.find('form').trigger('submit.prevent');
    await flushPromises();

    const cancelBtn = body.findAll('button').find(b => b.text() === 'Cancel' && b.element.closest('.confirm-dialog-content'));
    await cancelBtn.trigger('click');
    await flushPromises();

    const savedLoans = repository.saveLoans.mock.calls[0][0];
    expect(savedLoans[0].loanName).toBe('TV Financing (renegotiated)'); // non-param edit kept
    expect(savedLoans[0].installmentsCount).toBe(3); // schedule regen discarded
    expect(savedLoans[0].installments[0].status).toBe('paid'); // prior paid status preserved
  });

  it('deletes a loan after confirming in the ConfirmDialog, and does not close on overlay click', async () => {
    const loan = makeCasualLoan();
    repository.getLoans.mockResolvedValue([loan]);

    const wrapper = mount(LoanTracker, { global: i18nStub });
    await flushPromises();

    const deleteBtn = wrapper.findAll('.action-icon-btn.danger')[0];
    await deleteBtn.trigger('click');
    await flushPromises();

    const overlay = document.body.querySelector('.modal-overlay');
    overlay.dispatchEvent(new Event('click', { bubbles: true }));
    await flushPromises();
    expect(document.body.querySelector('.confirm-dialog-content')).not.toBeNull();

    const body = new DOMWrapper(document.body);
    const confirmBtn = body.findAll('button').find(b => b.text() === 'Delete Loan' && b.element.closest('.confirm-dialog-content'));
    await confirmBtn.trigger('click');
    await flushPromises();

    expect(repository.saveLoans).toHaveBeenCalled();
    const savedLoans = repository.saveLoans.mock.calls[0][0];
    expect(savedLoans).toHaveLength(0);
  });

  it('recording a repayment on a casual loan appends it to the payments ledger', async () => {
    const loan = makeCasualLoan();
    repository.getLoans.mockResolvedValue([loan]);

    const wrapper = mount(LoanTracker, { global: i18nStub });
    await flushPromises();

    await wrapper.find('.loan-card').trigger('click');
    await flushPromises();

    const body = new DOMWrapper(document.body);
    await body.find('#payment-amount-input').setValue(40);
    await body.find('#payment-date-input').setValue('2026-02-01');

    await body.find('.inline-payment-form form').trigger('submit.prevent');
    await flushPromises();

    expect(repository.saveLoans).toHaveBeenCalled();
    const savedLoans = repository.saveLoans.mock.calls[0][0];
    expect(savedLoans[0].payments).toHaveLength(1);
    expect(savedLoans[0].payments[0]).toMatchObject({ amount: 40, date: '2026-02-01' });
  });
});
